version: '3'

services:
###> doctrine/doctrine-bundle ###
  db:
    image: mariadb:10.6
    restart: unless-stopped
    container_name: db
    hostname: db
    environment:
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      retries: 5
      test:
        - CMD
        - mysqladmin
        - ping
        - "-h"
        - localhost
      timeout: 20s
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 12345:80
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db_data:
###< doctrine/doctrine-bundle ###
